# Generated by Django 3.2.13 on 2022-06-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0009_line_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCartMailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reminder_mail_date', models.DateTimeField(blank=True, null=True)),
                ('second_reminder_mail_date', models.DateTimeField(blank=True, null=True)),
                ('third_reminder_mail_date', models.DateTimeField(blank=True, null=True)),
                ('product_history', models.CharField(blank=True, max_length=10000, null=True)),
                ('history_status', models.CharField(max_length=100)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='basket.basket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
