# Generated by Django 3.2.13 on 2023-01-18 12:02

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20230118_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=oscar.models.fields.NullCharField(max_length=200, unique=True, verbose_name='Titolo EN'),
        ),
    ]
