# Generated by Django 3.2.13 on 2023-01-18 12:08

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_alter_product_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=oscar.models.fields.NullCharField(max_length=200, verbose_name='Titolo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=oscar.models.fields.NullCharField(max_length=200, verbose_name='Titolo EN'),
        ),
    ]
