# Generated by Django 3.2.13 on 2022-05-13 08:59

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_it', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('slug_it', models.SlugField(max_length=255)),
                ('slug_de', models.SlugField(max_length=255)),
                ('slug_fr', models.SlugField(max_length=255)),
                ('slug_es', models.SlugField(max_length=255)),
                ('seo_title_it', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title tag it')),
                ('seo_title_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title tag de')),
                ('seo_title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title tag fr')),
                ('seo_title_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title tag es')),
                ('search_description_it', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description it')),
                ('search_description_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description de')),
                ('search_description_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description fr')),
                ('search_description_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description es')),
            ],
            options={
                'verbose_name': 'Base Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='First Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254)),
                ('page', models.CharField(blank=True, max_length=250, null=True, verbose_name='From Page')),
                ('product', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product of interest')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('message', models.TextField(verbose_name='Message')),
                ('privacy', models.BooleanField(default=False, verbose_name='Privacy')),
                ('date_received', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Form Contact',
                'verbose_name_plural': 'Form Contacts',
            },
        ),
        migrations.CreateModel(
            name='FormWorkWithUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='First Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254)),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Area of interest')),
                ('file', models.FileField(upload_to='files_work_with_us/%Y/%m/%d/')),
                ('message', models.TextField(verbose_name='Message')),
                ('privacy', models.BooleanField(default=False, verbose_name='Privacy')),
                ('date_received', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Form Work With Us',
                'verbose_name_plural': 'Form Work With Us',
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_description_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description de'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description es'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description fr'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_description_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description it'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title tag de'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title tag es'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title tag fr'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title tag it'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slug_de',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='slug_es',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='slug_fr',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='slug_it',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MIR', max_length=200, verbose_name='Name')),
                ('addresses', wagtail.core.fields.StreamField([('address', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, label='Title Address', null=True, required=False)), ('address', wagtail.core.blocks.TextBlock(blank=True, null=True, required=False)), ('emails', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.EmailBlock(blank=True, null=True, required=False))]))), ('phones', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('phone', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False))]))), ('lat', wagtail.core.blocks.CharBlock(blank=True, label='Latitude', null=True, required=False)), ('lon', wagtail.core.blocks.CharBlock(blank=True, label='Longitude', null=True, required=False))]))], blank=True, null=True)),
                ('mymir_registration', models.URLField(blank=True, help_text='MyMir Registration URL', null=True)),
                ('mymir_login', models.URLField(blank=True, help_text='MyMir Login URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Youtube URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Linkedin URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
