# Generated by Django 3.2.13 on 2022-06-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220610_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormWorkWithUs',
        ),
    ]
