# Generated by Django 3.2.13 on 2022-06-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_formworkwithus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCustomerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='First Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='Message')),
                ('privacy', models.BooleanField(default=False, verbose_name='Privacy')),
                ('date_received', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Form Customer Service',
                'verbose_name_plural': 'Form Customer Service',
            },
        ),
    ]
