# Generated by Django 3.2.13 on 2022-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_formcustomerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Analytics ID'),
        ),
    ]
