# Generated by Django 3.2.13 on 2022-07-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sitesettings_model_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='model_privacy',
        ),
    ]
