# Generated by Django 3.2.13 on 2022-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_sitesettings_model_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('privacy', models.BooleanField(default=False)),
                ('date_subscribe', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Form Newsletter',
                'verbose_name_plural': 'Form Newsletters',
            },
        ),
        migrations.AddField(
            model_name='formcontact',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Newsletter'),
        ),
    ]
