# Generated by Django 3.2.13 on 2022-08-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220714_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_test',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Analytics TEST ID'),
        ),
    ]
