# Generated by Django 3.2.13 on 2022-07-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='cf',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='piva',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Partita Iva'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='requested_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
