# Generated by Django 3.2.13 on 2022-07-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20220705_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='menu_order',
            field=models.IntegerField(default=1),
        ),
    ]
