# Generated by Django 3.2.13 on 2022-07-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_country_menu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='menu_order',
        ),
    ]
