# Generated by Django 3.2.13 on 2022-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Consent Newsletter'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='Consent Privacy'),
        ),
    ]
