# Generated by Django 3.2.13 on 2022-08-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian')], default='en', max_length=10, verbose_name='Preferred language'),
        ),
    ]
