# Generated by Django 3.2.13 on 2022-06-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200801_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='cf',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='notes',
            field=models.TextField(blank=True, default='-', help_text='Tell us anything we should know when delivering your order.', null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='piva',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Partita Iva'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='requested_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
