# Generated by Django 3.2.13 on 2022-07-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20220610_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='terms_and_conditions_expressly',
            field=models.BooleanField(default=False, help_text='Pursuant to and for the purposes of Articles 1341 and 1342 of the Italian Civil Code, the Professional Customer declares that he/she expressly and unconditionally accepts Articles 5 (transport and delivery), 8 (Errors and limitations of liability) and 10 (Applicable law and competent court).', verbose_name='Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Terms and Conditions'),
        ),
    ]
