# Generated by Django 3.2.13 on 2022-07-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20220704_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='terms_and_conditions_expressly',
            field=models.BooleanField(default=False, verbose_name='Pursuant to and for the purposes of Articles 1341 and 1342 of the Italian Civil Code, the Professional Customer declares that he/she expressly and unconditionally accepts Articles 5 (transport and delivery), 8 (Errors and limitations of liability) and 10 (Applicable law and competent court).'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='I accept General Terms and Conditions of Sale'),
        ),
    ]
